name: deploy app

on:
  push:
    branches: [main]
    paths:
      - 'index.html'
  workflow_dispatch:


jobs:
  deploy:
    runs-on: self-hosted
    env:
      DOCKER_USER: ${{ vars.DOCKER_USER }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Debug path
        run: pwd && ls -la

      - name: Rebuild clean
        run: docker compose down || true
      - name: Remove old images
        run: docker system prune -af

      - name: Deploy app
        run: docker compose up  -d --build