name: deploy app

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    env:
      DOCKERHUB_USER: ${{ vars.DOCKER_USERNAME }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Deploy app
        run: docker compose up -d --build