name: Devsecops End to End Pipeline

on:
    workflow_dispatch:
    push:
        branches: [main]
jobs:
    # CI (Contineus integration with securityscaning)
    code-quality:
        uses: ./.github/workflows/code-quality.yml
    secret-scan:
        uses: ./.github/workflows/secret-scan.yml
        secrets: inherit
    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml
    docker-lint:
        uses: ./.github/workflows/docker-lint.yml
    image-scan:
        uses: ./.github/workflows/image-scan.yml
        secrets:
          DOCKER_USERNAME: ${{ vars.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
    # build once the ssecurity scan is passed
    build:
        needs: [code-quality, secret-scan, dependency-scan, docker-lint, image-scan]
        uses: ./.github/workflows/docker-build-push.yml
        secrets:  
          DOCKER_USERNAME: ${{ vars.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         
