name: setting and using job outputs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  set-date:
    runs-on: ubuntu-latest

    # create today jobs output 
    outputs:
      today: ${{ steps.date.outputs.today }}

    steps:
      - name: Get today's date
        id: date
        run: echo "today=$(date)" >> $GITHUB_OUTPUT

  use-date:
    runs-on: ubuntu-latest
    needs: set-date

    steps:
      - name: Use output from previous job
        run: echo "Date from previous job: ${{ needs.set-date.outputs.today }}