name: Gurudeen Kori
role: DevOps Engineer (Learning Phase)
experience_years: 0
learning: true

tools:
  - Docker
  - Kubernetes
  - GitHub Actions
  - Jenkins
  - Terraform

hobbies: [coding, learning, watching-tech-videos]
