name: Portfolio

on:
  push:
    branches: [main]

permissions:
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Upload website files as artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
