name: Portfoliyo

on: 
    push:
        branches: [main]
    workflow_dispatch:
permissions:
    id-token: read
    pages: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment :
            name: github-pages
            url: ${{ steps.deployments.outputs.page_url }}step
        steps:
            # get the code from the portfolio repository
            - name: Checkout code
              uses: actions/checkout@v4
            # setup github pages
            - name: Set up github pages
              uses: actions/configure-pages@v4
         
            # static code artifact
            -name: Deploy to github pages
             uses: actions/deploy-pages@v4
            # deploy to github pages
            - name: Deploy to github pages  
              uses: actions/deploy-pages@v4
