name: Print Secrets

on :
    Workflow_dispatch:

jobs:

    print-secrets-variablrs:
        runs-on: self-hosted
        env:
            DOCKER_USER: ${{ vars.DOCKER_USER }}
        steps:
            - name: Print secrets
              run: echo "Docker username:${{vars.DOCKER_USER}}"