name: schedule
on: 
  schedule:
    - cron: 56 20 * * *

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: hello $USER 
        run: hello this is $USER
      - name: create your own file 
        run: mkdir $USER

  os_information:
    runs-on: ubuntu-latest
    steps:
      - name: your os in formation
        run: cat /etc/os-release
